### ISSUE TITLE
Neverclicker: Doing random stuff on desktop / locking up 

### ISSUE THREAD

**Issue by zeusome** [c0gent/NeverClicker#17]
Main problem I am having is I leave Neverclicker on and come back hours later, or next morning, and it has opened up random things on desktop. Or related issues.. not doing what it is supposed to do. 

Left it on overnight and this morning it was at main username/password login screen (I started it on char select screen ... how did it even get to login screen?), was stuck, and had typed some letters into my username box. When I went to close NWinter window, it then it locked up PC completely and I had to hard reboot using powerbutton. I wish I could have gotten the log file. 

A few times when I went to close or stop NClicker it locked and went into "Not Responding" mode. 
In general it works for awhile, and then behaves badly while I am afk :( 

NOTE: This is really an extension and elaboration of Issue #12

**Comment by c0gent** [comment]
I've already fixed a bunch of the problems causing this. Later tonight I'll put up a release to download which should fix at least most of the problems for now. 

I'm also redesigning a few of the core systems which will fix a number of other things. That should be ready in a week or two depending how much time I have to work on it.

**Comment by c0gent** [comment]
The custom profession tasks is a part of that big revamp as well.

**Comment by c0gent** [comment]
@zeusome:

This should fix the freezes and hopefully the random behaviors. Let me know how it works for you...

https://github.com/c0gent/NeverClicker/releases/tag/v0.5.3

**Comment by zeusome** [comment]
Great alright, ive got it. Will run overnight and let you know how it works.

**Comment by zeusome** [comment]
The new 0.5.3 version is working better overall. Has not gone astray and clicked outside window so far.

**Comment by c0gent** [comment]
Good to hear. If it doesn't happen again in the next few days we'll close this.
