### ISSUE TITLE
Cursor not on the right coordinate

### ISSUE THREAD

**Issue by Roflmaostomp** [c0gent/NeverClicker#19]
Im using the resolution, direct 9 and everything as suggested, but the cursor at the start of the process, when it tries to click on the top part to go to the top of the list of the characters, it misses it

**Comment by c0gent** [comment]
Tweak the settings mentioned in the [Screen Resolution](https://github.com/c0gent/NeverClicker/blob/master/README.md#screen-resolution) section.

**Comment by Roflmaostomp** [comment]
---

De: Nick Sanders notifications@github.com
Enviado: martes, 11 de octubre de 2016 08:17:06 p. m.
Para: c0gent/NeverClicker
Cc: julian-alz; Author
Asunto: Re: [c0gent/NeverClicker] Cursor not on the right coordinate (#19)

Closed #19https://github.com/c0gent/NeverClicker/issues/19.

##

**Comment by c0gent** [comment]
@julian-alz: I see that my character must have been typing into alliance chat. Was the message repeated a bunch or just once? Thanks for letting me know by the way.

**Comment by Roflmaostomp** [comment]
Saw it twice man, im Mort btw

Obtener Outlook para Androidhttps://aka.ms/ghei36

On Wed, Oct 12, 2016 at 12:29 AM -0700, "Nick Sanders" <notifications@github.com<mailto:notifications@github.com>> wrote:

Reopened #19https://github.com/c0gent/NeverClicker/issues/19.

##

**Comment by c0gent** [comment]
Oh hey Mort.

Thanks for letting me know, I guess it glitches out sometimes. If it continues I'll see what I can do about it.

Did you ever get NeverClicker working for yourself?

**Comment by c0gent** [comment]
Delete the  `C:\Users\{{User Name}}\Documents\NeverClicker` folder then download and run the newest version (0.6.0). It should fix your problem. Please let me know if it doesn't.
